server:
  port: 8080

spring:
  application:
    name: druid-demo
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall_tiny
    driver-class-name: com.mysql.cj.jdbc.Driver

###################### MyBatis 配置#########################
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
#  type-aliases-package:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
